# Generated by Django 6.0.8 on 2026-08-18 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('electric', 'Electric'), ('executive', 'Executive')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('status_label', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('interior_story', models.TextField(blank=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('features', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('featured_on_home', models.BooleanField(default=False)),
                ('card_image_url', models.URLField(blank=True, max_length=500)),
                ('card_image_key', models.CharField(blank=True, max_length=255)),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('hero_image_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=16)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('object_key', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(max_length=200)),
                ('object_position', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default_exterior', models.BooleanField(default=False)),
                ('is_default_interior', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Gallery media',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
