# Generated by Django 6.0.8 on 2026-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymedia',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='card_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='hero_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
