# Generated by Django 6.0.8 on 2026-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_eyebrow', models.CharField(blank=True, max_length=120)),
                ('home_headline', models.CharField(blank=True, max_length=200)),
                ('home_cta_label', models.CharField(blank=True, max_length=80)),
                ('home_narrative', models.TextField(blank=True)),
                ('about_intro', models.TextField(blank=True)),
                ('founder_quote', models.TextField(blank=True)),
                ('founder_name', models.CharField(blank=True, max_length=120)),
                ('brand_history', models.TextField(blank=True)),
                ('values', models.JSONField(blank=True, default=list)),
                ('studio_blurb', models.TextField(blank=True)),
                ('test_drive_intro', models.TextField(blank=True)),
                ('privacy_copy', models.TextField(blank=True)),
                ('response_time_copy', models.CharField(default='under 24 hours', max_length=120)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
        migrations.CreateModel(
            name='StudioLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('studio_name', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='StudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_display_name', models.CharField(default='Kaka Motors', max_length=120)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Studio settings',
                'verbose_name_plural': 'Studio settings',
            },
        ),
    ]
