# Generated by Django 6.0.8 on 2026-08-18 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(max_length=80)),
                ('preferred_date', models.DateField()),
                ('consent', models.BooleanField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.studiolocation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
